config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :plans
  get '/search' => 'plans#search', as: :search
  resources :profiles
  resources :users
  get ':id' => 'users#show', as: :user_profile
  get ':id/setting' => 'users#edit', as: :user_setting
  match ':id/setting' => 'users#update', via: [:put, :patch]
  root 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :plans
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  belongs_to :profile

  validate :is_future



  def past?
   start_time && end_time < Date.today
  end
  # validate the future origin of the date
  def is_future
     errors.add("appointment time", "cannot be in the past") if start_time && end_time && past?
  end

  # searchkick text_start: [‘title’], text_start: [‘intro’]

  def self.search(term)
     where("title LIKE ? ", "%#{term}%" )
   end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :plans, through: :user

  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' },
                             url: '/system/:class/:attachment/:id_partition/:style/:hash.:extension',
                             path: ':rails_root/public/system/:class/:attachment/:id_partition/:style/:hash.:extension',
                             hash_secret: '<get_use_rake_secret>'
  validates_attachment :avatar, content_type: { content_type: /\Aimage\/.*\Z/ },
                                size: { in: 0..1.megabytes }
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :plans, dependent: :destroy
  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile
  before_create :build_profile #creates profile at user registration
  validates :username, presence: true, length: { minimum: 3, maximum: 16 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def after_sign_in_path_for(resource)
    profile_path(current_user.id)
  end

  def after_sign_up_path_for(resource)
    profile_path(current_user.id)
  end


  # protected
  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:username, :field_of_teaching, :city, :email, :password, :remember_me)}
  #   devise_parameter_sanitizer.for(:sign_in) {|u| u.permit(:email, :password, :remember_me)}
  #   devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:username, :field_of_teaching, :city, :email, :password, :remember_me)}
  # end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:search]

  # GET /plans
  # GET /plans.json
def index

  if params[:category].blank?
    @plans = Plan.all.order("created_at DESC")
  else
    @category_id = Category.find_by(name: params[:category]).id
    @plans = Plan.where(category_id: @category_id).order("created_at DESC")
 end
end

def show
  @plan = Plan.find(params[:id])
  respond_to do |format|
    format.html
    format.pdf do
      pdf = PlansPdf.new(@plan, view_context)
      send_data pdf.render, filename:
      "plan_#{@plan.created_at.strftime("%d-%m-%Y")}.pdf",
      type:"application/pdf"
    end
  end
end

def search
	@plans = Plan.search(params[:query]).paginate(page: params[:page], per_page: 3)
	if request.xhr?
		render :json => @plans.to_json
	else
		render :search
	end
end

def new
  @plan = current_user.plans.build
end

def create
  @plan = current_user.plans.build(plan_params)
  if @plan.save
    redirect_to @plan
  else
    render 'new'

 end
end

def edit
end

def update
 if @plan.update(plan_params)
   redirect_to @plan

else
  render 'edit'
end
end

def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:title, :start_time, :end_time, :warm_up, :intro, :drill, :practice, :gamesandactivities, :review, :category_id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
def show
   @profile = current_user.profile
   @attributes = Profile.attribute_names - %w(id user_id created_at updated_at)
   
end


def edit

end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :field_of_teaching, :city, :email, :password, :password_confirmation, :remember_me)
  end

  def account_update_params
    params.require(:user).permit(:username, :field_of_teaching, :city, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_owner!
  before_filter :set_user, only: [:show, :edit, :update]

  def show
  end

  def edit
    @user.build_profile if @user.profile.nil?
  end

  def update
    if @user.update(user_params)
      redirect_to user_profile_path(@user)
    else
      render 'edit'
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(profile_attributes: [:id, :avatar])
    end

    def authenticate_owner!
      redirect_to root_path unless user_signed_in? && current_user.to_param == params[:id]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
  { success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice: 'alert-info'
  }[flash_type.to_sym] || flash_type.to_s
end


def profile_avatar_select(user)
  return image_tag user.avatar.url(:medium),
                   id: 'image-preview',
                   class: 'img-responsive img-circle profile-image' if user.avatar.exists?
  image_tag 'default-avatar.jpg', id: 'image-preview',
                                  class: 'img-responsive img-circle profile-image'
end

end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
  return '' if resource.errors.empty?

  messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
  sentence = I18n.t('errors.messages.not_saved',
  count: resource.errors.count,
  resource: resource.class.model_name.human.downcase)

  # for Bootstrap 3 pay attention to the classes in the "div"

  html = <<-HTML
  <div class="card pink lighten-3">
  <button class="btn-floating btn-large waves-effect waves-light close" aria-hidden="true">&times;</button>
  <h5 class="white-text">#{sentence}</h5>
  #{messages}</div>
  HTML
  html.html_safe
 end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.slim
doctype html
html lang="en"
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no" name="viewport" /
    title
      img alt=("Unsplashed background img 2") src="assets/logo.png" >/
      | TeePees
    /! CSS
    link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" /
    link href='https://fonts.googleapis.com/css?family=Fredericka+the+Great' rel='stylesheet' type='text/css'/
  body

    header
      nav.top-nav.lime.accent-3
       .container#home.section.scrollspy
        .nav-wrapper
            a#logo-container.brand-logo.hbrand.center href="#"

       .container
         a#nav-mobile.button-collapse.top-nav.full-hide-on-large-only

       ul#slide-out.side-nav.fixed
          li.logo style="width: 250px; height: 200px;"
           a href="#home"
             img alt=('logo on the sidebar') src="assets/emg_hero.png" style="width: 180px; height: 180px;"/
          li.card
           a href="#about"  ABOUT
          li.card

            - if current_user
               =link_to "Log out",  destroy_user_session_path , method: :delete
            - else
               =link_to "Log in", new_user_session_path


               =link_to "Register", new_user_registration_path

          li.card
          .btn-group
            =link_to "PLANS", plans_path, class:"btn btn-default"

          li.card
           a href="#!"  LINKS
          li.card

       a.button-collapse data-activates="slide-out" href="#"
        i.mdi-navigation-menu


    main
     #index-banner.parallax-container
      .section.no-pad-bot
        .container#home
          p.notice= notice
          p.alert= alert
          br/
          br/
          .row.left style="font-size: 52px;font-style: normal;font-weight: normal;height: auto;line-height: 64px;text-decoration: none;text-transform: uppercase;width: auto;font-family: 'Fredericka the Great', sans-serif; color: white;"
            h5.header.col.s12.light
            | TEACHING PLANS YOU'LL LOVE
          br/
          br/
          =react_component('Login', text: 'hello!')
      .parallax
        img alt=("background img 1") src="assets/chalkboard5.jpg" /
     .container
      .section
        /! Icon Section
        .row
          .col.s12.m4
            .icon-block
              h2.center.brown-text
                i.material-icons.infoicon loyalty
              h5.center EASY TO USE
              p.light just click and build the teaching plans for your amazing classes
          .col.s12.m4
            .icon-block
              h2.center.brown-text
                i.material-icons.infoicon group
              h5.center FOR ALL TEACHERS
              p.light you can be an ace in any discilpline: there is no limit to the plan builder
          .col.s12.m4
            .icon-block
              h2.center.brown-text
                i.material-icons.infoicon satellite
              h5.center ACCESSABLE
              p.light no matter if you work in China or NewYork: TP will be always there to help you out
     .parallax-container.valign-wrapper
      .section.no-pad-bot
        .container
          .row.center
            h5.quote.col.s12.light
              |
              br/
              |
      .parallax
        img alt=("Unsplashed background img 2") src="assets/chalkboard5.jpg" /
     .container
      .section
        .row
          .col.s12.center#about.section.scrollspy
            h3
              i.mdi-content-send.lime-text
            h4 ABOUT
            p.center-align.light.z-depth-5
            |  After having taught for even as little as a couple of months you might find yourself have had gathered millions of classroom ideas, aids and carricula. But organizing and keeping track of all that material becames a real struggle: endless folders on the computer, scattered paper notes and bookmarks. A lot gets lost on the way or simply forgotten. TeePees is an answer to all those challenges. It enables you to keep track of everything you have created. You can take notes on the go. Design your own teaching helpers. Even set a timer for each part of the class. Try out this amazing set of tools and go enjoy your awesome work, Teacher!
            |  You deserve it!
     .parallax-container.valign-wrapper
      .section.no-pad-bot
        .container
          .row.center
            h5.quote.col.s12.light
              |
              br/
              |
      .parallax
        img alt=("Unsplashed background img 3") src="assets/chalkboard5.jpg" /
    footer.page-footer.lime.accent-3
      .container
        .row
            h4.black-text.center Connect
            .col.s12.center

                a.white-text href="https://twitter.com/katmryc"
                  img alt=("my logo") src="assets/tw.png" /

                a.white-text href="https://www.facebook.com/profile.php?id=100010805376820"
                  img alt=("my logo") src="assets/fb.png" /

                a.white-text href="https://www.linkedin.com/in/katmrycak"
                   img alt=("my logo") src="assets/linl.png" /
      .footer-copyright
        .container
          | developed by   |
          a#logo-container.brand-logo href="https://katmryc.com"
             img alt=("my logo") src="assets/logo.png" /


    /! Scripts

app/views/layouts/_navigation.slim
nav.top-nav.lime.accent-3
 .container#home.section.scrollspy
  .nav-wrapper
      a#logo-container.brand-logo.hbrand.center href="#"

 .container
   a#nav-mobile.button-collapse.top-nav.full-hide-on-large-only

 ul#slide-out.side-nav.fixed
    li.logo style="width: 250px; height: 200px;"
     a href="#home"
       img alt=('logo on the sidebar') src="assets/emg_hero.png" style="width: 180px; height: 180px;"/
    li.card
     a href="#about"  ABOUT
    li.card

      - if current_user
         =link_to "Log out",  destroy_user_session_path , method: :delete
      - else
         =link_to "Log in", new_user_session_path


         =link_to "Register", new_user_registration_path

    li.card
    .btn-group
      =link_to "PLANS", plans_path, class:"btn btn-default"

    li.card
     a href="#!"  LINKS
    li.card

 a.button-collapse data-activates="slide-out" href="#"
  i.mdi-navigation-menu

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teaching Plans</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
</body>
</html>

app/views/plans/_form.slim
.form
= form_for(@plan) do |f|
  - if @plan.errors.any?
    #error_explanation
      h2
        = pluralize(@plan.errors.count, "error")
        | Please, correct these fields:
      ul
        - @plan.errors.full_messages.each do |message|
          li= message



  .container
   .row
     form.col.s3
     .field.col.s12
        = f.text_field :title

   .row
     form.col.s3
      .field.col.s6
       = f.label :start_time
       br/
       = f.text_field :start_time

      .field.col.s6

       = f.label :end_time
       br/

       = f.text_area :end_time

   .row
     .input-field
      = f.text_area :warm_up

   .row
    .input-field
      = f.text_area :intro


   .row
    .input-field
      = f.text_area :drill

   .row
    .input-field
      = f.text_area :practice


   .row
    .input-field
      = f.text_area :gamesandactivities


   .row
    .input-field
      = f.text_area :review

   .row.center
      = f.button :submit

app/views/plans/edit.slim
.card
  |EDIT YOUR PLAN
.card
 = render 'form'


ul
  li.card
  .btn-group
    = link_to "SHOW", @plan, class:"btn btn-default"

  li.card
  .btn-group
    = link_to "BACK", plans_path, class:"btn btn-default"

app/views/plans/index.slim
.container
 .row
  .card.col.m12
    .col.s9
      h3 Your Plans
    .col.s3.center
      .button
       = link_to 'New Plan', new_plan_path,class:"btn btn-default"
    .row
     .col.m5.center
     p#notice= notice

 .row
  -@plans.each do |plan|
      .card.col.s12.m5
        .row
         .col.s9.blue
          h5.white-text Title:
          = link_to plan.title, plan
         .col.s3.green
          h5.white-text Added date:
          = plan.created_at.strftime('%b %d, %Y')

         .col.m5.center.pink
          = truncate(plan.intro, length: 200)

        .row.center.yellow
          .btn-group
            = link_to "SHOW", plan, class:"btn btn-default lime accent-3"
            = link_to 'Edit', edit_plan_path(plan), class:"btn btn-default"
            = link_to 'Destroy', plan, method: :delete, class:"btn btn-default"


            / .card.enhanced style=("background-color: transparent")
            /        .cyan
            /          .row.middle-xs
            /            .col-xs-10
            /              .box
            /                .card-title.white-text.truncate.modal-close.action-marker-goto.action-gallery-search data-workpad-key="IEcSbeeHpecFuGDB3SzuAd" style=("padding:0.2rem 1rem 0rem;")
            /                  = @plan.title
            /                  span.green-text.text-lighten-4 style=("font-size: 0.8rem; font-weight: 500;")
            /                p.card-description.truncate.card-keywords.light.action-gallery-search
            /
            /        .card-content.grey.lighten-4 style=("margin-bottom: 8px; padding: 5px 10px; font-size: 0.8rem;")
            /          .row.middle-xs
            /            .col-xs.start-xs
            /              .box
            /                h4 Content
            /                = truncate(plan.intro, length: 200)
            /        .card-content.grey.lighten-4 style=("margin-bottom: 8px; padding: 5px 10px; font-size: 0.8rem;")
            /            .row.middle-xs
            /               .col-xs.start-xs
            /                 .box
            /                   h4 Price
            /                   = @note.price
            /        .card-content.teal.lighten-3 style=("padding-top: 0;  padding-bottom: 0; background-color: #fff;")
            /          .card-details style=("padding: 10px 0px;")
            /            .row.between-xs style=("width: 100%; margin:0;")
            /              .col-xs
            /                .box
            /                   = link_to "SHOW", plan, class:"btn btn-default lime accent-3"
            /
            /              .col-xs.end-xs
            /                .box
            /                = link_to 'Edit', edit_plan_path(plan), class:"btn btn-default"
            /
            /              .col-xs.end-xs
            /                .box
            /                = link_to 'Destroy', plan, method: :delete, class:"btn btn-default"

app/views/plans/new.slim
.container
 .section
  .row.center
    h5 Plan
 = render 'form'

.row
 .btn-group.center
  = link_to 'Back', profile_path(current_user), class: "btn btn-default lime"

app/views/plans/search.slim
= react_component 'PlansContainer', { plansPath: plans_path(:json), searchPath: search_path }

app/views/plans/show.slim
.container
  .section
   .row

            p
              strong Title:
              = @plan.title


   .row
     .col.s12.m3
            p
              strong Start time:
              = @plan.start_time
     .col.s12.m3
            p
              strong End time:
              = @plan.end_time
   .row
            p
              strong Warm up:
              = @plan.warm_up
   .row
            p
              strong Intro:
              = @plan.intro
   .row
            p
              strong Drill:
              = @plan.drill
   .row
            p
              strong Practice:
              = @plan.practice
   .row
            p
              strong Gamesandactivities:
              = @plan.gamesandactivities
   .row
            p
              strong Review:
              = @plan.review

.section.center
 .row
  .btn-group
  = link_to 'EDIT', edit_plan_path(@plan),class: "btn btn-default lime"

 .row
  .btn-group
  = link_to 'BACK', profile_path, class: "btn btn-default lime"

 .row
  .btn-group
   = link_to 'DOWLOAD PDF', plan_path(@plan.id, :format => "pdf"), class: "btn btn-default lime"

app/views/profiles/edit.slim
p#notice= notice
 =render 'application/_navigation'

.container
 .section
  .row
   .col.s12.m6
    h1 Hello

    =current_user.username


  .row
   .col.s12.m6
    .btn-group

    = link_to "Search", search_path, class: "btn btn-default lime"

  .row
   .col.s12.m6
    .btn-group
    = link_to 'NEW PLAN', new_plan_path, class: "btn btn-default lime"

  .row
   .col.s12.m6
    .btn-group
    = link_to "Log out",  destroy_user_session_path , method: :delete, class: "btn btn-default lime"


  .row
    .col.md.4
            ul.list-group
            - Category.all.each do |category|
              li= link_to category.name, plans_path(category: category.name), class:"list-group-item"

.container
 .section
  .row
   .col.s12.m6
  /  - Plan.all.each do |plan|
  /    li= link_to plan.title, plans_path(plan: plan.title), class: "list-group-item"
    =render 'form'

app/views/profiles/show.slim
p#notice= notice
 =render 'application/_navigation'

.container
 .section
  .row
   .col.s12.m6
    h1 Hello

    =current_user.username

  .row
    .col-md-12
      .img-circle



  .row
   .col.s12.m6
    .btn-group

    = link_to "Search", search_path, class: "btn btn-default lime"

  .row
   .col.s12.m6
    .btn-group
    = link_to 'NEW PLAN', new_plan_path, class: "btn btn-default lime"

  .row
   .col.s12.m6
    .btn-group
    = link_to "Log out",  destroy_user_session_path , method: :delete, class: "btn btn-default lime"

  .row
   .col.s12.m6
    .btn-group
    - if @user == current_user
    = link_to 'Edit Profile', edit_profile_path(current_user.id)


/   .row
/     .col.md.4
/             ul.list-group
/             - Category.all.each do |category|
/               li= link_to category.name, plans_path(category: category.name), class:"list-group-item"
/
/ .container
/  .section
/   .row
/    .col.s12.m6
/   /  - Plan.all.each do |plan|
/   /    li= link_to plan.title, plans_path(plan: plan.title), class: "list-group-item"
/     =render 'form'

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>